/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conways.game.of.life;

public class App {

    public static void main(String[] args) {
    int[][] inicializacion = {
        {0,0,0,0,0},
        {0,1,0,0,0},
        {0,0,0,0,0},
        {0,0,0,0,0},
        {0,1,0,1,1}
    };

        GameOfLife game = new GameOfLife(inicializacion, new B2(), new S());

        
        System.out.println("|ETAPA 1: \n" + game.toString());

        System.out.print(game.cantVecinosVivos(1, 1));

        game.siguienteGeneracion();

        System.out.println("|ETAPA 2: \n" + game.toString());
    }
}
